[workspace]
members = ["crates/d7s_db"]

[package]
name = "d7s"
version = "0.1.0"
description = "Database client"
authors = ["Rob <robertazzopardi@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[package.metadata.bundle]
identifier = "com.robertazzopardi.d7s"

[workspace.dependencies]
keyring = { version = "3.6.3", features = ["apple-native"] }

[dependencies]
d7s_db = { path = "crates/d7s_db" }
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
unicode-width = "0.2"
tokio = { version = "1.47.0", features = ["rt-multi-thread", "macros"] }
keyring.workspace = true
