[package]
name = "d7s"
version = "0.1.0"
description = "Database client"
authors = ["Rob <robertazzopardi@icloud.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
sqlx = "0.8.6"
unicode-width = "0.2"
